osx_image: xcode9.2
language: objective-c
podfile: Example/Podfile
notifications:
  email: false
before_install:
- gem install bundler
- bundle install
- bundle update fastlane
script:
- bundle exec fastlane test
after_success:
- bash <(curl -s https://codecov.io/bash)
- GITHUB_TOKEN=$GITHUB bundle exec fastlane push
env:
  global:
  - secure: cceSD6ja+i5UQaCtJXWGjSh0PhmI7ZrSLQUh/xxY1l/uhlE38Z4xAXiANcPHTAB7wqVj2ihJ8uvKwtZ5HSbLYaBAdnlMOMF6Jf6SDjgF9/18mxrJ1PSs7Y1QxQ2vtChCAw0W5RnMYh4Wyy41cSos9c2K+H9zlpgv3lOBOTRvXSGO/LbqnbiKIbvYmWNC37jAYWmkoIAK9B9aGin/wbVQTCIZkBuPdPlouQbWznXbs+bZ8kteBGrTbaOJzcUZzS+ub1Maw2bZXNeDO4mw3ycimMcyUi3dJTkjV+BKea4QbLjNNfH/gmwx1loflR7am2lQ6/r2oxWoxVLhI7/A9t7KVcdjkYr+9hMfaEvDf5NSrx3n0VY+aKSvuOmURDEWPCc8pfeG3sJaKkynjHuVH5rdlv1lYFN5/CT3Y1IxXWa5wC1wCsRoKfcsJs/S5NzUM/wTeVRC680PIQqIxlQO+2m6afItSSa39TRurQ0SzsCevKzk3G+wTWoSTAVnYdFlGxy6DakO4SSjLKiu0jwkpFUi+vuuReNxE6YOQxn251uXN+SM6vXgoHdVS3Qfm4oQnECnMuZOnsx1BuFEWnQFTNdEvVrqKjMIglwzhOk2tbqUYq5FviUjQYwI4zWY/cYmrHJqW1XmW6Nd8tnKs2vuZ2Z3iyEqWnoVS3eJv2T2VwoFrEU=
  - secure: JBP76VK2mdzlklywZF/WvF4BcS11aOn8v3bLyZjC0YSyVB8NrzGVtftGWBXZ5Z2ZA2ShVP0oxgjmTe+FIZ79HrF1V2dpoD/HWVZmmJ2bnc0OMe4uHK/nG/Y5fJtjpTbzS3kg++LkQGIHpGyZo3204a4JFWzxvQWaL4UltzSvhcqDhcOSqw3Np/ap40q2C/ySrcmsfG2tm04jjKaNQCofpPD72ivrZ88sjkHkVkXs6IBvVDjoNbqcib4+vlWS2A4V6Yspvj8jIUPvCW0SwNOrHaF7BMNxjVCf++sErRP61I17MlQHvvMn2n2bGMU501TwKEYCZXC9fzMNMkrDXnTlY8kB4GjQEJCL0xWr4VKvu6xr/xAjj6hprpOhz6Owtxy2aYBN0a0yp2YNgd4g+/+/dDfVDduc7+3lS9eKm2dDcJlu5DP0HS+/C0WVSTYDE/BSEkcsyTxPXGFhtS71CKBGeZhDfdlumqXuRsDSManohTdVunrFHoI1wJ0QztTh87PkORxLbb90PbUkO4kuSZco8z08TrGrlHQukK0DrOPfMiHsA0Xz0GD3Hn3vpqSRgfx3lGDBNvXpQslnVCTvtfRmPA7ALkOmdXXZQI+UDhGxhPGLfMYh1kNxQh9ZzYTMWknxng41rXEyFK4imlDRhu7Ib74MKNj1+DFG8i81E/5STEE=
